# Generated by Django 5.0.6 on 2024-05-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='64846bfba23740df9c339e698ea0a673', editable=False, max_length=16)),
                ('buyer_id', models.BigIntegerField(default=0)),
                ('buyer_delivery_address', models.TextField(blank=True, null=True)),
                ('buyer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.TextField(blank=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.TextField(blank=True, default=0.0)),
                ('product_total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('product_total_unit', models.BigIntegerField(blank=True, default=0)),
                ('product_category', models.CharField(blank=True, default=0, max_length=255)),
                ('product_category_name', models.TextField(blank=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('mode_of_payment', models.CharField(default='Cash on Delivery', max_length=255)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('seller_id', models.TextField(default=0)),
                ('order_delivered', models.BooleanField(default=False)),
                ('order_shipped', models.BooleanField(default=False)),
                ('order_placed_by_seller', models.BooleanField(default=False)),
                ('seller_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Handle_By_Seller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='6301737086464fbbb25c29bf0a48b5ba', editable=False, max_length=16)),
                ('buyer_id', models.BigIntegerField(default=0)),
                ('buyer_delivery_address', models.TextField(blank=True, null=True)),
                ('buyer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.TextField(blank=True, default=0.0)),
                ('product_total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('product_total_unit', models.BigIntegerField(blank=True, default=0)),
                ('product_category', models.TextField(blank=True, default=0)),
                ('product_category_name', models.TextField(blank=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('mode_of_payment', models.CharField(default='Cash on Delivery', max_length=255)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('seller_id', models.TextField(default=0)),
                ('order_delivered', models.BooleanField(default=False)),
                ('order_shipped', models.BooleanField(default=False)),
                ('order_cancelled', models.BooleanField(default=False)),
                ('order_placed_by_seller', models.BooleanField(default=False)),
                ('order_returned', models.BooleanField(default=False)),
                ('order_returned_reason', models.TextField(blank=True)),
                ('order_returned_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_returned_fund', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('seller_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.BigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='seller/product_images/')),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_bio', models.TextField(blank=True, null=True)),
                ('seller_image', models.ImageField(blank=True, null=True, upload_to='seller_images/')),
                ('seller_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_address', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterDummy.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='masterDummy.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
