# Generated by Django 2.2.28 on 2024-06-19 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(editable=False, max_length=16)),
                ('product_name', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.TextField()),
                ('product_category', models.TextField()),
                ('product_category_name', models.TextField()),
                ('product_total_units', models.TextField()),
                ('product_units', models.TextField()),
                ('product_total_price', models.TextField()),
                ('buyer_id', models.CharField(max_length=255)),
                ('buyer_delivery_address', models.CharField(max_length=255)),
                ('buyer_full_name', models.CharField(max_length=255)),
                ('buyer_email', models.CharField(max_length=125)),
                ('seller_id', models.TextField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_fee', models.CharField(max_length=125)),
                ('mode_of_payment', models.CharField(default='Cash on Delivery', max_length=125)),
                ('order_placed_by_buyer', models.BooleanField(default=True)),
                ('order_delivered', models.BooleanField(default=False)),
                ('order_pending', models.BooleanField(default=True)),
                ('order_shipped', models.BooleanField(default=False)),
                ('total_order_items_counter', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Order_For_Seller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(editable=False, max_length=16)),
                ('product_name', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.TextField()),
                ('product_category', models.TextField()),
                ('product_category_name', models.TextField()),
                ('product_total_units', models.TextField()),
                ('product_units', models.TextField()),
                ('product_total_price', models.TextField()),
                ('buyer_id', models.CharField(max_length=255)),
                ('buyer_delivery_address', models.CharField(max_length=255)),
                ('buyer_full_name', models.CharField(max_length=255)),
                ('buyer_email', models.CharField(max_length=125)),
                ('seller_id', models.TextField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_fee', models.CharField(max_length=125)),
                ('mode_of_payment', models.CharField(default='Cash on Delivery', max_length=125)),
                ('order_placed_by_buyer', models.BooleanField(default=True)),
                ('order_delivered', models.BooleanField(default=False)),
                ('order_pending', models.BooleanField(default=True)),
                ('order_shipped', models.BooleanField(default=False)),
                ('order_cancelled_by_seller', models.BooleanField(default=False)),
                ('total_order_items_counter', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Order for Seller',
                'verbose_name_plural': 'Orders for Sellers',
            },
        ),
        migrations.CreateModel(
            name='OrderArchive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(editable=False, max_length=16)),
                ('product_names', models.TextField(blank=True, null=True)),
                ('product_descriptions', models.TextField(blank=True, null=True)),
                ('product_prices', models.TextField(blank=True, null=True)),
                ('product_categories', models.TextField(blank=True, null=True)),
                ('product_category_names', models.TextField(blank=True, null=True)),
                ('product_total_units', models.TextField(blank=True, null=True)),
                ('product_units', models.TextField(blank=True, null=True)),
                ('product_total_price', models.TextField(blank=True, null=True)),
                ('buyer_id', models.CharField(blank=True, max_length=2555, null=True)),
                ('buyer_delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=125, null=True)),
                ('seller_id', models.TextField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=125, null=True)),
                ('mode_of_payment', models.CharField(default='Cash on Delivery', max_length=125)),
                ('original_ordered_items_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('order_placed_by_buyer', models.BooleanField(default=True)),
                ('order_delivered', models.BooleanField(default=False)),
                ('order_pending', models.BooleanField(default=True)),
                ('order_shipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True, default='N/A')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.BigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='seller/product_images/')),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_bio', models.TextField(blank=True, null=True)),
                ('seller_image', models.ImageField(blank=True, null=True, upload_to='seller_images/')),
                ('seller_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_address', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterDummy.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('username', models.CharField(blank=True, default='', max_length=125, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='masterDummy.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
