# Generated by Django 5.0.4 on 2024-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Order_To_Buyer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=16)),
                ('product_name', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.TextField()),
                ('product_category', models.TextField()),
                ('product_category_name', models.TextField()),
                ('product_total_units', models.TextField()),
                ('product_units', models.TextField()),
                ('product_total_price', models.TextField()),
                ('buyer_id', models.CharField(max_length=255)),
                ('buyer_delivery_address', models.CharField(max_length=255)),
                ('buyer_full_name', models.CharField(max_length=255)),
                ('buyer_email', models.CharField(max_length=125)),
                ('seller_id', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('delivery_fee', models.CharField(max_length=125)),
                ('mode_of_payment', models.CharField(max_length=125)),
                ('order_placed_by_buyer', models.BooleanField()),
                ('order_delivered', models.BooleanField()),
                ('order_pending', models.BooleanField()),
                ('order_shipped', models.BooleanField()),
                ('order_cancelled_by_seller', models.BooleanField()),
            ],
        ),
    ]
