# Generated by Django 5.0.6 on 2024-05-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order_for_seller',
            name='order_id',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
