# Generated by Django 5.0.6 on 2024-05-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order_items_counter',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
