# Generated by Django 5.0.6 on 2024-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='50c405a389c1430390b3c4285a509da3', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='order_handle_by_seller',
            name='order_id',
            field=models.CharField(default='840bbac6a14f465495b007fe7917dace', editable=False, max_length=16),
        ),
    ]
