# Generated by Django 5.0.6 on 2024-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0002_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_placed_by_seller',
            new_name='order_placed_by_buyer',
        ),
        migrations.RenameField(
            model_name='order_handle_by_seller',
            old_name='order_placed_by_seller',
            new_name='order_placed_by_buyer',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='8c3fcec774ee44d7ba1053a2d39e3240', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='order_handle_by_seller',
            name='order_id',
            field=models.CharField(default='ec6bd9b419ca4cb58fbc45ae03ff2a3c', editable=False, max_length=16),
        ),
    ]
