# Generated by Django 5.0.6 on 2024-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0002_order_total_order_items_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_for_seller',
            name='total_order_items_counter',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='original_ordered_items_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
