# Generated by Django 5.0.4 on 2024-05-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0003_orderarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderarchive',
            name='order_date',
        ),
    ]
