# Generated by Django 5.0.4 on 2024-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0004_remove_orderarchive_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderarchive',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='orderarchive',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderarchive',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderarchive',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderarchive',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderarchive',
            name='order_id',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
