# Generated by Django 5.0.6 on 2024-06-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0004_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
