# Generated by Django 5.0.4 on 2024-05-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0005_remove_orderarchive_archived_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Final_Order_To_Buyer',
        ),
    ]
