# Generated by Django 5.0.6 on 2024-06-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0005_alter_product_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specification',
            new_name='specifications',
        ),
    ]
