# Generated by Django 5.0.4 on 2024-05-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0006_delete_final_order_to_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderarchive',
            name='buyer_delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='buyer_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='buyer_id',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='delivery_fee',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='mode_of_payment',
            field=models.CharField(default='Cash on Delivery', max_length=125),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='order_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='order_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='order_placed_by_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='order_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_category_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_total_price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_total_units',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='product_units',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='seller_id',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderarchive',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
