# Generated by Django 5.0.6 on 2024-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0006_rename_specification_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
