# Generated by Django 5.0.4 on 2024-05-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0007_orderarchive_buyer_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderarchive',
            old_name='product_category',
            new_name='product_categories',
        ),
        migrations.RenameField(
            model_name='orderarchive',
            old_name='product_category_name',
            new_name='product_category_names',
        ),
        migrations.RenameField(
            model_name='orderarchive',
            old_name='product_description',
            new_name='product_descriptions',
        ),
        migrations.RenameField(
            model_name='orderarchive',
            old_name='product_name',
            new_name='product_names',
        ),
        migrations.RenameField(
            model_name='orderarchive',
            old_name='product_price',
            new_name='product_prices',
        ),
    ]
