# Generated by Django 5.0.6 on 2024-06-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0007_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
