# Generated by Django 5.0.6 on 2024-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0011_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, default='', max_length=125, null=True),
        ),
    ]
