# Generated by Django 5.0.6 on 2024-06-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDummy', '0012_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
